Header Section
GSG-CF04/Food-City pull request #29
Opened 2021-11-30 11:14 UTC by xAbeer

Relates #10

2021-11-30 11:24 UTC, yaqootturman requested changes

2021-11-30 11:24 UTC, yaqootturman commented on home/index.js
> +            link.style.animation=`newLink  0.5s ease forwards ${index/7+0.7}s`
Its not pretty good, maybe you should talk about this and suggest sth else

2021-11-30 11:24 UTC, yaqootturman commented on index.html
> +                  <img src="assets/Logo.png">
The img should be a camel case too, logo not Logo

2021-12-01 10:00 UTC, yaqootturman approved these changes

2021-12-01 10:04 UTC, hussambanna approved these changes

2021-12-01 10:11 UTC, ahmedirheem approved these changes

2021-12-01 10:12 UTC, merged