create form to info order html and css
GSG-CF04/Food-City pull request #40
Opened 2021-12-05 14:41 UTC by xAbeer

Relates #24

2021-12-05 15:39 UTC, yaqootturman requested changes

2021-12-05 15:39 UTC, yaqootturman commented on order/order.js
> +submitData.addEventListener('click',(e)=>{
before submit data check if the user enter required fields or not, if he isn't give him a warning but if he entered all of them and clicked submit give him a success pop up message

2021-12-05 20:44 UTC, yaqootturman approved these changes

2021-12-06 07:11 UTC, ahmedirheem approved these changes

2021-12-06 08:02 UTC, hussambanna approved these changes

2021-12-06 09:09 UTC, merged